import { useEffect, useState } from "react";
import { MapContainer, Marker, Popup, TileLayer, useMap } from "react-leaflet";
import L from "leaflet";
import { analyze, api, getApiError } from "./api/client";

const icon = new L.Icon({ iconUrl: "https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png", iconSize: [25, 41], iconAnchor: [12, 41] });
function Recenter({ item }) { const map = useMap(); useEffect(() => { if (item) map.setView([item.latitude, item.longitude], 13); }, [item, map]); return null; }

export default function App() {
  const [file, setFile] = useState(null), [demo, setDemo] = useState(true), [status, setStatus] = useState("EMPTY"), [result, setResult] = useState(null), [selected, setSelected] = useState(null), [error, setError] = useState("");
  const [metadata, setMetadata] = useState({ survey_id: "DEMO_SURVEY_01", latitude: 9.9252, longitude: 78.1194, source: "simulated" });
  const [stats, setStats] = useState({ total: 0, high: 0, medium: 0, low: 0, by_type: {} });
  useEffect(() => { api.get("/api/statistics").then(({ data }) => setStats(data)).catch(() => {}); }, [result]);
  async function run() { if (!file) return setError("Choose a sonar image first."); setStatus("UPLOADING"); setError(""); try { setStatus("PROCESSING"); const { data } = await analyze(file, metadata, demo); setResult(data); setSelected(data.detections[0] || null); setStatus("SUCCESS"); } catch (e) { setStatus("ERROR"); setError(getApiError(e)); } }
  const center = selected ? [selected.latitude, selected.longitude] : [metadata.latitude, metadata.longitude];
  return <main><header><div><p className="eyebrow">SIH26057 / SONAR INTELLIGENCE</p><h1>Underwater Marine Debris <em>Intelligence</em></h1><p className="subtitle">AI-powered side-scan sonar anomaly detection</p></div><div className="health"><span className="dot" /> Backend ready <strong>{demo ? "DEMO / SAMPLE DATA" : "AI ANALYSIS"}</strong></div></header>
    <section className="toolbar"><div className="mode"><button className={demo ? "active" : ""} onClick={() => setDemo(true)}>Demonstration Mode</button><button className={!demo ? "active" : ""} onClick={() => setDemo(false)}>AI Analysis</button></div><span className={`status ${status.toLowerCase()}`}>{status}</span></section>
    <section className="grid"><aside className="panel upload"><h2>Analyze a survey pass</h2><label className="drop"><input type="file" accept="image/*" onChange={e => setFile(e.target.files[0])} /><span className="drop-icon">↑</span><b>{file ? file.name : "Drop sonar image here"}</b><small>PNG, JPG, TIFF up to 20 MB</small></label><label>Survey ID<input value={metadata.survey_id} onChange={e => setMetadata({ ...metadata, survey_id: e.target.value })} /></label><div className="coords"><label>Latitude<input type="number" value={metadata.latitude} onChange={e => setMetadata({ ...metadata, latitude: e.target.value })} /></label><label>Longitude<input type="number" value={metadata.longitude} onChange={e => setMetadata({ ...metadata, longitude: e.target.value })} /></label></div><button className="primary" onClick={run}>{demo ? "Run sample analysis" : "Run AI analysis"} <span>→</span></button>{error && <p className="error">{error}</p>}</aside>
      <section className="panel viewer"><div className="panel-head"><div><h2>Sonar viewer</h2><p>{result ? `${result.image.width} × ${result.image.height} px / ${result.processing_time_ms} ms` : "Awaiting an analysis pass"}</p></div>{result?.mode === "demo" && <span className="sample-tag">DEMO / SAMPLE DATA</span>}</div>{result ? <div className="image-wrap"><img src={`${api.defaults.baseURL}${result.image.annotated_url}`} alt="Annotated sonar analysis with detection boxes" /></div> : <div className="empty-view"><span>◉</span><p>Upload a sonar image to inspect detections</p></div>}</section>
    </section>
    <section className="stats"><h2>Survey overview</h2><div className="stat-row"><Stat label="Total anomalies" value={stats.total} /><Stat label="High priority" value={stats.high} accent="high" /><Stat label="Medium priority" value={stats.medium} accent="medium" /><Stat label="Low priority" value={stats.low} accent="low" />{["ghost_net", "shipwreck", "pipe", "cylinder", "debris"].map(type => <Stat key={type} label={type.replace("_", " ")} value={stats.by_type?.[type] || 0} />)}</div></section>
    <section className="lower"><section className="panel table-panel"><div className="panel-head"><div><h2>Detection register</h2><p>Prototype anomaly score / confidence-filtered</p></div><div className="reports"><button onClick={() => window.open(`${api.defaults.baseURL}/api/reports/${metadata.survey_id}/csv`)}>↓ CSV</button><button onClick={() => window.open(`${api.defaults.baseURL}/api/reports/${metadata.survey_id}/json`)}>↓ JSON</button></div></div><table><thead><tr><th>Object</th><th>Confidence</th><th>Priority</th><th>Coordinates</th><th>Source</th></tr></thead><tbody>{result?.detections.map(item => <tr key={item.id} className={selected?.id === item.id ? "selected" : ""} onClick={() => setSelected(item)}><td><b>{item.object_type.replace("_", " ")}</b></td><td>{Math.round(item.final_confidence * 100)}%</td><td><span className={`priority ${item.priority.toLowerCase()}`}>{item.priority}</span></td><td>{item.latitude.toFixed(4)}, {item.longitude.toFixed(4)}</td><td>{item.metadata_source === "simulated" ? "Sample coordinates" : item.metadata_source}</td></tr>) || <tr><td colSpan="5" className="empty-row">No detections yet</td></tr>}</tbody></table></section><section className="panel map-panel"><div className="panel-head"><div><h2>Survey map</h2><p>OpenStreetMap / geographic association</p></div></div><MapContainer center={center} zoom={10} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Recenter item={selected} />{result?.detections.map(item => <Marker key={item.id} position={[item.latitude, item.longitude]} icon={icon} eventHandlers={{ click: () => setSelected(item) }}><Popup><b>{item.object_type}</b><br />{item.priority} / {Math.round(item.final_confidence * 100)}%<br />Sample Coordinates</Popup></Marker>)}</MapContainer></section></section>
  </main>;
}
function Stat({ label, value, accent }) { return <div className={`stat ${accent || ""}`}><strong>{value}</strong><span>{label}</span></div>; }
